### ISSUE TITLE
Crash of Ulozto Service after download is started

### ISSUE THREAD

**Issue by fisero** [gabonator/SynologyUlozTo#11]
After download is started Ulozto Service is stoped with next log:
![image](https://cloud.githubusercontent.com/assets/24524906/21604257/8675a7d2-d1a2-11e6-81c2-19be925b378e.png)

As a result only small file is downloaded (84KB) - used URL is direct to file download page, so only this is downloaded I guess.

**Comment by gabonator** [comment]
tried to fix this issue, could you please try reinstalling ulozto.spk (package)?

**Comment by fisero** [comment]
![image](https://cloud.githubusercontent.com/assets/24524906/21604788/7db735b8-d1a5-11e6-837b-cb2f6b143999.png)

**Comment by gabonator** [comment]
try now

**Comment by fisero** [comment]
Grade job! Now downloading has been started.
