### ISSUE TITLE
poškozené soubory u "FAST" stahování

### ISSUE THREAD

**Issue by rave77** [gabonator/SynologyUlozTo#18]
Ahoj, od určité doby, asi po nějaké poslední aktualizaci, přestalo fungovat vícesegmentové stahování FAST... respektive ono funguje, ale takto stažené filmy nehrajou správně, kostičkují a po chvíli přehrávání padnou, formát je poškozený, dříve bylo vše OK. Pokud je dám stahovat klasicky, přes download station s omezením 300kb/s, jsou v pořádku. Je to jen můj problém? Mám DS215j a všechen SW aktuální.

**Comment by gabonator** [comment]
Ahoj, viem o tomto probleme. Niekedy to stiahne subor bez chyb a niekedy (pravdepodobne na rozhrani 1MB segmentov) su tam chyby. Nestudoval som to blizsie. S aktualizaciou by to nemalo mat nic spolocne, od urciteho okamihu su tieto problemy vyraznejsie. Momentalne nemam cas fixovat to, nemame tu nejakeho programatora co by mi s tym pomohol?

**Comment by rave77** [comment]
Díky za info. Rád bych pomohl, ale bohužel nejsem programátor. Každopádně tenhle projekt je skvělá vychytávka a zasloužila by si podpořit ;-) Snad se najde někdo šikovný, kdo bude mít chuť a čas udržovat to při životě...

**Comment by gabonator** [comment]
vcera som nasiel tu chybu, pls. vedel by si to otestovat?

**Comment by rave77** [comment]
Vyzkousel jsem. Ve stazenem souboru uz nejsou chyby, hraje OK. Ale rychlost stahovani je rovna free verzi, tedy omezeno na 300. Prohlizec sice ukazuje stazeni napr za 30 minut a rychlost stahovani 2M, ale realne se to stahuje stejne 3 hodiny, coz jak prepocitam odpovida omezeni na free...

**Comment by gabonator** [comment]
U mna to ide pekne, 1480kBps pri piatich slotoch, pouzil si FAST download, alebo iba Download/Play?

**Comment by rave77** [comment]
Starou verzi 7.2 jsem odinstaloval a nainstaloval aktualni 8.1 a pouzil jsem FAST...
Jeste na necem zkusim....

**Comment by gabonator** [comment]
Ked chces, mozes skusit aj portable balicek:
https://github.com/gabonator/SynologyUlozTo/blob/master/portable.zip

ked si na windowse, staci ti spustit "spusti.bat", alebo zavolaj"node server.js". Stahovac ti potom pojde priamo z pocitaca
