### ISSUE TITLE
Problém s instalací

### ISSUE THREAD

**Issue by frantisekflachs** [gabonator/SynologyUlozTo#25]
![2022-01-15 17_47_43-Flachy-srv](https://user-images.githubusercontent.com/5648173/149630229-2531dfbe-b738-4a61-b65f-3e5dc254e965.png)

Dobrý den,

prosím o opravu případně o radu.
V DSM 7.x již není dostupná tato možnost: Package Center -> Settings -> Allow installation of package published by: "Any publisher" - viz přiložený prtsc. Tudíž "ulozto.spk" nelze nainstalovat s chybovou hláškou "Invalid file format. Please contact the package developer."
Současně nejnovější Node.js je ve verzi v14, bude váš tool funkční v této verzi?

Díky za pomoc s istalací.

S pozdravem,
František Flachs

**Comment by gabonator** [comment]
Ahoj, tento vyhladavaci engine ako aj stahovaci tool uz viac ako dva roky nefunguje. Ulozto zmenili hlasovu captchu a nemal som cas to upravit. Existuju ale ine programy s podobnou funkcionalitou, aj ked bez integracie do synology. Treba hladat…
