### ISSUE TITLE
Ulozto plugin

### ISSUE THREAD

**Issue by Meenya** [gabonator/SynologyUlozTo#5]
Ahojte,

protože přestalo fungovat stahování, stáhnul jsem znova host a dlm a také balíček "Ulozto Service". Vyhledávání mi jde pouze přes prohlížeč přes 8034, v Download stationu vůbec. Po chvíli se dokonce "Ulozto service" zastaví. 

Už jsem odinstaloval a zase nainstaloval node, pluginy host a dlm i balíček. Stále stejné.

Nějaký nápad, co s tím? Děkuju

**Comment by svasek** [comment]
A co ti to napise do logu? Najdes ho u nainstalovaneho balicku "UloztoService"?

**Comment by Meenya** [comment]
![1](https://cloud.githubusercontent.com/assets/17547868/17217614/3d663c12-54e5-11e6-9c0d-b9cda6405b11.JPG)

Už mi nejde balíček ani spustit. Ani po reinstallu balíčku.

Node 4.2.6-0158
DSM 6.0.1-7393 Update 2

**Comment by svasek** [comment]
Zkuste prosim restart celeho Synology.

**Comment by Meenya** [comment]
To jsem udělal už 2x. Zkusím do třetice.

**Comment by svasek** [comment]
Zkusil bych tento postup:
 * Odinstalovat balicek "Synology service"
 * Restart zarizeni
 * Nainstalovat balicek "Synology service"

**Comment by Meenya** [comment]
Provedl jsem.
Balíček nyní běží, ale nelze nic vyhledat přes Download station. Log níž je po vyhledávání přes DS.
![2](https://cloud.githubusercontent.com/assets/17547868/17218668/de7984c6-54e8-11e6-9c47-83d4d3cadd39.JPG)

Níže je další log po vyhledávání přes 8034 přes prohlížeč.
![3](https://cloud.githubusercontent.com/assets/17547868/17218770/4a840010-54e9-11e6-8c3c-f465adba5a60.JPG)

**Comment by svasek** [comment]
UloztoService bezici na portu 8034 se pouziva k prolomeni captcha ne k vyhledavani.
K vyhledavani v Download center se pouziva ulozto.dlm.

**Comment by Meenya** [comment]
Rozumím, jen tam ověřuji, jestli to běží, nebo ne. Každopádně v DS to nefachá.

Pro jistotu - má port 8034 v prohlížeči vypadat takto?
![4](https://cloud.githubusercontent.com/assets/17547868/17219066/49845fa6-54ea-11e6-89e6-51e241646f6b.JPG)

**Comment by svasek** [comment]
Ano, to vypada asi v poradku.

**Comment by svasek** [comment]
Jaky je stav? Mohu tuto issue zavrit?

**Comment by Meenya** [comment]
Bohužel, nevyřešeno. Už si nevím rady, co mě napadlo, tak jsem zkusil.

**Comment by svasek** [comment]
No popravde nevim, co vam poradit.
Muzete mi prosim popsat cely postup, ktery vede k teto chybe?

**Comment by Meenya** [comment]
Klidně se můžeme tykat ;)
No jak jsem popisoval výše.
Port 8034 mi funguje v prohlížeči, ale ne v Download stationu. Přes DS nenajde vůbec nic. Zkoušel odinstalovat i nainstalovat host i dlm, balíček. Mezitím to také restartovat.

Výše jsem posílal i chybu, kterou to háže v protoku při vyhledávání přes web. Přes DS to ani nic nezapíše do protokolu.

**Comment by Meenya** [comment]
Nějaký nápad? Zkusil jsem vše znova odinstalovat, restartovat, a nainstalovat a stále stejné.

**Comment by svasek** [comment]
Bohuzel me napady dosly. Jen nechapu, proc vubec pristupujete na port 8034. Ja tam vubec nelezu, ten je tam je pro prolomeni captcha kodu. Vse, vcetne vyhledavani a stahovani, se dela v Download Station.

**Comment by Meenya** [comment]
Protože v Download Stationu to nefunguje - ani ťuk. Kdežto na tom portu ano - z toho tedy plyne, že plugin běží, ale neumí k tomu nějak přistoupit Download Station.

**Comment by svasek** [comment]
Z toho plyne, že beží ta služba, ale nefunguje plugin pro DS.

**Comment by Meenya** [comment]
Ten hlásí "Spuštěno". Lze to tedy nahodit nějak ručně jako to bylo dříve, tzn. příkazem "node server.js"?

**Comment by svasek** [comment]
Ale mluvime kazdy o necem jinem. Node.js je ta UloztoService bezici na portu 8034.
Nainstalujte si podle navodu ulozto.dlm a ulozto.host. Pak zkuste vyhledavani a stahovani v DS.

**Comment by Meenya** [comment]
Aha. To jsem dělal už asi 3x, vždy podle návodu a nic. Kontroloval jsem i velikosti souborů podle návodu a ty sedí.

**Comment by Meenya** [comment]
A pokud přidám odkaz do Download stationu ručně, to řeší balíček "Ulozto service"? Stáhne to totiž soubor o velikosti 60 kB, přitom Ulozto service běží...

**Comment by horsikus** [comment]
Ahoj,
narazil jsem na stejny problem. Doplnek jsem dnes nainstaloval dle instrukci (hostovani, hledani, service).  V centru balicku je ulozto service videt jako bezici, ale v Download station se nic z ulozto nevyhleda.

V logu servisu je jen ze bezi na portu 8034. Stranka na tomto portu bezi a pri psani textu do policka se dohledavaji texty pod nim. Nasledne ale dochazi k zastaveni balicku. V logu je potom neco o spatnem tokenu.

Rucni kopirovani ulozto.cz linku do Download station take nefunguje. Stahne se evidentne jen html obsah stranky.

synology ds214play, DSM aktualizovane, doplněk stažen dnes z githubu, tj. posledni verze

**Comment by svasek** [comment]
Bohuzel Ulozto prekopali kompletne stranky, takze je treba dost zasadni upravy cele logiky.
Momentalne na to nemame cas, sorry.

**Comment by horsikus** [comment]
Ok. Diky za info a drzim palce at se povede doplnek aktualizovat.

**Comment by Meenya** [comment]
To jsem rád, že to teda není u mě. 
V pohodě, i tak díky za pár měsíců příjemného sosání.

Nakonec jsem nainstaloval JDownloader. Sice neumí captcha crack, ale sosám do NAS. Lze zadat účet na uložtu, pak není třeba zadávat captcha. Instalace snadná. Doporučuji Putty (SSH), přes telnet to úplně nešlo.

Odkaz zde:
https://support.jdownloader.org/Knowledgebase/Article/View/52/0/install-jdownloader-on-nas-and-embedded-devices

**Comment by horsikus** [comment]
Ahoj,

k tomu JDownloaderu .. Jde to ted naistalovat jako standardni balicek. Staci do zdroju balicku pridat  https://spk.netzbaer.de/  Zatim Beta. Ale zda se funguje.

**Comment by gabonator** [comment]
Ahojte, updatol som plugin. Dajte vediet ci vam to ide.

**Comment by gabonator** [comment]
Plugin bol po update otestovany, zatvaram issue
