### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by Belabu** [gabonator/SynologyUlozTo#6]
Dobrý den,
máte v plánu v projektu pokračovat? Chtěl jsem to zkusit sám, bohužel si neporadím s jejich zašifrovaným JSONem.

**Comment by gabonator** [comment]
Ahoj, ked zacne obdobie dazdov tak sa do toho pustim - budem travit viac casu pred telkou :) kym je vonku teplo tak sa mi moc nechce za pocitac sadat. Mas ku tomu nejaku analyzu? Co vlastne vsetko pomenili?

**Comment by Belabu** [comment]
No analýzu jako takovou k tomu nemám. Šel jsem krok po kroku (jenom service) a jejich JSON jsem nakonec dohromady dal. Klíč je hodnota posledního záznamu v jsonu, ale odkazy které to vrátí, vypadá asi takto /file-tracking/3ee31d31f4ac11121fb4d0452d9f58dd04c3f77c3b1618f739784f4b44e342f111e1e6fc477b075ed295a7ed341a47a9 a zatím visím tu.

**Comment by gabonator** [comment]
Ok, uz som na to prisiel, oni toho vela nezmenili, trosku zmenili format jquery JSONu a trosku v inom formate su aj udaje ku kazdemu filmu. Dam update kam som sa stihol dostat...

**Comment by gabonator** [comment]
Ok, tak uz to vsetko ide, mozete testovat...

**Comment by svasek** [comment]
Great job!
Az se k tomu dostanu, tak to testnu ;)

**Comment by Belabu** [comment]
Super, jede to. Díky

**Comment by gabonator** [comment]
@Belabu, dakujem za otestovanie, zatvaram issue. Keby si nasiel nejake chyby, vytvor novu...
